# Generated by Django 3.2 on 2021-04-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
